import { fix3, type PointXY } from "./geometry.js";
import { randomId } from "./random-id.js";
import type { MeasuredGradientSegment, SVGElementFn, SVGElementProxy, SVGLinearGradientProxy, SVGPathProxy, SVGRadialGradientProxy, SVGRectProxy } from "./types.js";

/**
 * Yes, I know the DOM has all the SVG stuff, but this is a domain specific abstraction.
 */
export class RickSVG {
	#nextId: number = 1;
	readonly #scratch: SVGGElement;
	public readonly defs: SVGDefsElement;
	readonly svg: SVGGElement;

	constructor(
		public readonly parent: HTMLElement,
		public readonly width: number,
		public readonly height: number,
		public readonly id = randomId("svg"),
	) {
		parent.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${ width } ${ height }" id="${ id }"><!-- generated by neuropride @ https://rickosborne.org/neuropride/ --><defs></defs><g class="scratch"></g></svg>`;
		this.svg = parent.querySelector(`#${ id }`)!;
		this.#scratch = Array.from(this.svg.querySelectorAll(".scratch") as NodeListOf<SVGGElement>)[ 0 ]!;
		this.defs = Array.from(this.svg.querySelectorAll("defs"))[ 0 ]!;
	}

	public el<E extends SVGElement, P extends SVGElementProxy<E>>(html: `<${ string }>`, type: SVGElementFn<E>, parent?: SVGElement | SVGElementProxy): P
	public el(html: `<${ string }/>`): SVGElementProxy;
	public el<E extends SVGElement, P extends SVGElementProxy<E>>(html: `<${ string }>`, type?: SVGElementFn<E>, parent?: SVGElement | SVGElementProxy): P {
		this.#scratch.innerHTML = html;
		const $el = this.#scratch.firstElementChild;
		if (!($el instanceof (type ?? SVGElement))) {
			console.error({ actual: $el, expected: type });
			throw new Error(`Expected ${ (type ?? SVGElement).name }`);
		}
		$el.parentElement?.removeChild($el);
		if (parent != null) {
			("$el" in parent ? parent.$el : parent).appendChild($el);
		}
		return svgProxy($el) as P;
	}

	private gradientStops(gradient: MeasuredGradientSegment[]): string[] {
		const stops: string[] = [];
		for (const [ color, start, end ] of gradient) {
			stops.push(`<stop offset="${ fix3(start) }%" stop-color="${ color }" />`);
			stops.push(`<stop offset="${ fix3(end) }%" stop-color="${ color }" />`);
		}
		return stops;
	}

	public group(
		block: (g: SVGElementProxy<SVGGElement>, s: RickSVG, id: string) => void,
		$parent = this.svg,
		id = randomId("g-"),
	): SVGElementProxy<SVGGElement> {
		const g = this.el(`<g id="${ id }"/>`, SVGGElement);
		$parent.appendChild(g.$el);
		block(g, this, id);
		return g;
	}

	public linearGradient(
		gradient: MeasuredGradientSegment[],
		[ x1, y1 ]: PointXY,
		[ x2, y2 ]: PointXY,
		gid = `${ this.id }-lg-${ this.#nextId++ }`,
	): SVGLinearGradientProxy {
		const stops = this.gradientStops(gradient);
		return this.el(`<linearGradient id="${ gid }" x1="${ fix3(x1) }" y1="${ fix3(y1) }" x2="${ fix3(x2) }" y2="${ fix3(y2) }" gradientUnits="userSpaceOnUse">${ stops.join("") }</linearGradient>`, SVGLinearGradientElement, this.defs);
	}

	public path(html: `<path${ string }/>`, parent?: SVGElement | SVGElementProxy): SVGPathProxy {
		return this.el(html, SVGPathElement, parent);
	}

	public radialGradient(
		gradient: MeasuredGradientSegment[],
		[ cx, cy ]: PointXY,
		[ ri, ro ]: PointXY,
		gid = `${ this.id }-rg-${ this.#nextId++ }`,
	): SVGRadialGradientProxy {
		const stops = this.gradientStops(gradient);
		return this.el(`<radialGradient id="${ gid }" cx="${ fix3(cx) }" cy="${ fix3(cy) }" fx="${ fix3(cx) }" fy="${ fix3(cy) }" fr="${ fix3(ri) }" r="${ fix3(ro) }" gradientUnits="userSpaceOnUse">${ stops.join("") }</radialGradient>`, SVGRadialGradientElement, this.defs);
	}

	public rect(html: `<rect${ string }/>`, parent?: SVGElement | SVGElementProxy): SVGRectProxy {
		return this.el(html, SVGRectElement, parent);
	}
}

export const svgProxy = <E extends SVGElement>($el: SVGElement): SVGElementProxy<E> => {
	return new Proxy({ $el } as SVGElementProxy<E>, {
		get(target, key) {
			if (key === "$el") {
				return target.$el;
			} else if (typeof key === "string") {
				return $el[ key as keyof SVGElement ];
			}
			return undefined;
		},
		set(target, key, newValue) {
			if (typeof key !== "string") {
				console.error("Unexpected symbol");
				return false;
			}
			target.$el.setAttributeNS(null, key, String(newValue));
			return true;
		},
	});
};
